### ISSUE TITLE
OpenAPI 3.1 Support

### ISSUE THREAD

**Issue by TomFreeman** [j-d-carmichael/boats#63]
**Is your feature request related to a problem? Please describe.**
Boats currently doesn't support OpenAPI 3.1 specs. Tracking any work required to support the latest spec.

**Describe the solution you'd like**
We're blocked by swagger-parser, which currently doesn't support OpenAPI 3.1, but other blockers I'm not aware of may exist.

* [ ] Wait for (or help with) swagger-parser supporting 3.1 See https://github.com/swagger-api/swagger-parser/issues/1535

**Describe alternatives you've considered**
Replace swagger-parser altogether, which seems overly intrusive.
Enable a command line flag that skips the use of swagger-parser for 3.1 specs, this sacrifices value.

**Additional context**
Thought I'd start tracking the dependencies needed to make OpenAPI 3.1 work here, specifically the webhooks feature would be useful for our use-case.

**Comment by j-d-carmichael** [comment]
https://github.com/APIDevTools/swagger-parser/issues/169

Seems this is on the radar

**Comment by j-d-carmichael** [comment]
Looks like https://stoplight.io/open-source/spectral/ offers 3.1 support on the validation

**Comment by j-d-carmichael** [comment]
@TomFreeman appologies for the delay on this one, the latest release has a new cli flag to skip validation.

**Comment by j-d-carmichael** [comment]
@TomFreeman   https://github.com/APIDevTools/swagger-parser/pull/187  and this should now be in the latest version of boats
