### ISSUE TITLE
`inject` helper `excludeChannel` and `includeOnlyChannels` params don't work with AsyncAPI document

### ISSUE THREAD

**Issue by gabormagyar** [j-d-carmichael/boats#70]
Alternate title:
## Injector `mapIndex` produces empty object for AsyncAPI document

**Describe the bug**
`inject([...])` filter functionality (`excludeChannel`, `includeOnlyChannels`) doesn't work, scope unclear.

**To Reproduce**
I'm using a standard, valid asyncAPI document, I'm not sure if it works for other things.

**Expected behavior**
`excludeChannel`, `includeOnlyChannels` params are respected

**Additional context**
I'm debugging into `Injector.ts`, and the offending code seems to be [the mapIndex function](https://github.com/j-d-carmichael/boats/blame/main/src/Injector.ts#L245). With this particular example at least, the problem seems to be that the `$ref` field is selected twice, once by the `Object.values(methods)` call, and then a second time by the explicit `methodToFileRef.$ref` accessor.

You can see in the debugger that `Object.values(methods)` is already a string array:
<img width="1048" alt="Screenshot 2022-03-25 at 13 41 10" src="https://user-images.githubusercontent.com/63397303/160122543-335d7b44-2e8a-435b-910c-22c7593438d3.png">

The result is that `methodToFileRef` is a string and `methodToFileRef.$ref` is undefined.
<img width="1049" alt="Screenshot 2022-03-25 at 13 29 53" src="https://user-images.githubusercontent.com/63397303/160121100-f319425e-419c-4677-9c24-d001fb46df19.png">

Therefore nothing ever gets added to `this.this.fileToRouteMap` so nothing ever passes the filter whitelist or blacklists. They have no entries to filter against.

**Comment by j-d-carmichael** [comment]
I will take a look into this over the weekend

**Comment by j-d-carmichael** [comment]
@gabormagyar after examining this evening, it looks like the inject helper has never been working for async api channels! Thank your for reporting it! 

This resolve the issue: https://github.com/j-d-carmichael/boats/blob/2.32.0/src/Injector.ts#L254

And tested here:  https://github.com/j-d-carmichael/boats/blob/2.32.0/srcASYNC2/index.yml#L19

**Comment by gabormagyar** [comment]
Thanks for the quick fix!
