### ISSUE TITLE
Version check takes a long time to timeout on runner with no internet

### ISSUE THREAD

**Issue by gabormagyar** [j-d-carmichael/boats#78]
Version check takes 5 minutes or more to timeout if boats is run on a CI runner with no internet access.

There should be an option to disable the version check entirely, not just the user interaction.

In the meantime I'm going to use patch-package as a workaround to remove the version check.

**Comment by p-mcgowan** [comment]
@gabormagyar as asnother option, if you set NODE_ENV=test the checker is skipped entirely

**Comment by gabormagyar** [comment]
NODE_ENV can affect quite a few things so I'd rather not use it in production

**Comment by j-d-carmichael** [comment]
Maybe the best solution would be a cli option that bypasses the version check.

To advertise the option, it would be output to the console when the check is in progress.

**Comment by j-d-carmichael** [comment]
Alrighty, pass -n and it will skip version check or --noVersionCheck in version 3.4 just released
