### ISSUE TITLE
Unable to exclude root paths from injection

### ISSUE THREAD

**Issue by Celleb** [j-d-carmichael/boats#86]
**Describe the bug**

When using the `inject` template, it is not possible to exclude root paths from injections.

**To Reproduce**

{{
  inject([
    { toAllOperations: {
      content: {
        security: [{ jwtToken: [] }]
      },
      excludePaths: [
          '/towns',
          '/'
        ]
      }
    }
  ])
}}

**Expected behavior**
The bundled specifications must not inject `security` into root paths. 

**Additional context**

**Comment by j-d-carmichael** [comment]
@Celleb could you please confirm on what path method types this is happening on?

eg: "paths/get.yml"

If not already, could you please confirm if this is also happening on a http verb starting with a letter after i

**Comment by j-d-carmichael** [comment]
By removing walker and replacing with a sync and then custom sort function to push any index to the top of the respective folder - this was causing a bug in that http actions, GET and DELETE were being rendered before the index file of the respective folder.


@Celleb  could you please confirm in 4.9.3 resolves your issue

**Comment by Celleb** [comment]
Build fails both with and without the `paths/get.yml`

**Comment by j-d-carmichael** [comment]
Could you provide a full example, please?

**Comment by Celleb** [comment]
Sorry, all is good. It had something to do with my node version. False Alarm!!!
